repositories:
- name: nuxeo
  url: https://packages.nuxeo.com/repository/helm-releases-public/

helmDefaults:
  timeout: 300
  wait: true

releases:
- name: nuxeo
  chart: nuxeo/nuxeo
  version: ~3.1.0
  values:
  - values/values-nuxeo.yaml.gotmpl
