# (C) Copyright 2019-2020 Nuxeo (http://nuxeo.com/) and others.
#
# Contributors:
#     Kevin Leturc <kleturc@nuxeo.com>
#     Anahide Tchertchian
#
apiVersion: skaffold/v2beta18
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  artifacts:
    - image: "$DOCKER_REGISTRY/nuxeo/nuxeo-explorer-export"
      context: Jenkinsfiles/explorer/export.d/docker
      kaniko:
        useNewRun: true
        singleSnapshot: true
        snapshot-mode: "time"
        buildArgs:
          NUXEO_VERSION: "{{.NUXEO_VERSION}}"
          BUILD_TAG: "{{.BUILD_TAG}}"
          SCM_REF: "{{.GIT_COMMIT}}"
          VERSION: "{{.VERSION}}"
          EXPLORER_CONNECT_CLID: "{{.EXPLORER_CONNECT_CLID}}"
          EXPLORER_CONNECT_URL: "{{.EXPLORER_CONNECT_URL}}"
          EXPORT_PACKAGE_CONNECT_CLID: "{{.EXPORT_PACKAGE_CONNECT_CLID}}"
          EXPORT_PACKAGE_CONNECT_URL: "{{.EXPORT_PACKAGE_CONNECT_URL}}"
          EXPORT_PACKAGE_LIST: "{{.EXPORT_PACKAGE_LIST}}"
  cluster:
    namespace: $CURRENT_NAMESPACE
    dockerConfig:
      secretName: jenkins-docker-cfg
    resources:
      requests:
        cpu: "1"
        memory: "3Gi"
      limits:
        cpu: "2"
        memory: "6Gi"
    nodeSelector:
      team: platform
    tolerations:
      - key: team
        operator: "Equal"
        value: platform
        effect: "NoSchedule"
