# (C) Copyright 2019-2020 Nuxeo (http://nuxeo.com/) and others.
#
# Contributors:
#     Kevin Leturc <kleturc@nuxeo.com>
#     Anahide Tchertchian
#
apiVersion: skaffold/v2beta18
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  artifacts:
    - image: "$DOCKER_REGISTRY/nuxeo/nuxeo-explorer-export"
      context: Jenkinsfiles/explorer/export.d/docker
      custom:
        buildCommand: |
          docker-buildx \
            --build-arg NUXEO_VERSION={{.NUXEO_VERSION}} \
            --build-arg BUILD_TAG={{.BUILD_TAG}} \
            --build-arg SCM_REF={{.GIT_COMMIT}} \
            --build-arg VERSION={{.VERSION}} \
            --secret id=EXPLORER_CONNECT_CLID,env=EXPLORER_CONNECT_CLID \
            --build-arg EXPLORER_CONNECT_URL={{.EXPLORER_CONNECT_URL}} \
            --secret id=EXPORT_PACKAGE_CONNECT_CLID,env=EXPORT_PACKAGE_CONNECT_CLID \
            --build-arg EXPORT_PACKAGE_CONNECT_URL={{.EXPORT_PACKAGE_CONNECT_URL}} \
            --build-arg EXPORT_PACKAGE_LIST={{.EXPORT_PACKAGE_LIST}} \
