name: "Setup Maven build"
description: "Performs the setup of required build tools (eg.: Maven, Java)"
inputs:
  java-version:
    description: the desired Java version
    default: "17"
    required: false
  java-distribution:
    description: the desired Java distribution
    default: "temurin"
    required: false
  maven-settings:
    description: the location of the custom Maven settings.xml file to install
    default: ".github/mvn/settings.xml"
    required: false
  cache-key-prefix:
    description: the prefix for the maven repository cache key (eg. to handle multiple maven caches within the same repository)
    default: "maven"
    required: false
runs:
  using: composite
  steps:
  - name: "Check for settings.xml override"
    shell: bash
    run: |
      MAVEN_SETTINGS_PATH="${{ inputs.maven-settings }}"
      if [ ! -f "$MAVEN_SETTINGS_PATH" ]; then
        echo "No custom Maven settings file found in the repository at: $MAVEN_SETTINGS_PATH. The default one will be used."
        MAVEN_SETTINGS_PATH="${{ github.action_path }}/settings.xml"
      fi
      echo "MAVEN_SETTINGS_PATH=$MAVEN_SETTINGS_PATH" >> $GITHUB_ENV
  - name: "Setup Java Build"
    uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@ffc4f9974da0c6fe311fb66e119547a2e8c126c8 #v12.0.0
    with:
      java-version: ${{ inputs.java-version }}
      java-distribution: ${{ inputs.java-distribution }}
      maven-settings: ${{ env.MAVEN_SETTINGS_PATH }}
